# Generated by Django 5.2.11 on 2026-02-12 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma'), ('un', 'Unidade'), ('dz', 'Dúzia'), ('cx', 'Caixa')], default='kg', max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fruta',
                'verbose_name_plural': 'Frutas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fruteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, default='')),
                ('endereco', models.CharField(blank=True, default='', max_length=500)),
                ('telefone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fruteira',
                'verbose_name_plural': 'Fruteiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('lote', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='inventory.fruta')),
                ('fruteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='inventory.fruteira')),
            ],
            options={
                'verbose_name': 'Item de Estoque',
                'verbose_name_plural': 'Itens de Estoque',
                'ordering': ['data_vencimento', 'fruteira', 'fruta'],
                'indexes': [models.Index(fields=['fruteira', 'data_vencimento'], name='inventory_e_fruteir_90fac5_idx'), models.Index(fields=['fruta', 'data_vencimento'], name='inventory_e_fruta_i_7c2379_idx')],
            },
        ),
    ]
